Update tracker_node.py
Alpaca-zip/ultralytics_ros pull request #15
Opened 2023-08-07 16:51 UTC by Gowresh7

Added a logic to handle 'bgr8a' encoding, usually found in simulation image sensors

2023-08-08 08:48 UTC, Alpaca-zip requested changes
Thank you @Gowresh7 for your Pull request!

Upon reviewing the code, I am contemplating the implications of merging this PR.

The current implementation I've written does not explicitly handle the encoding of the subscribed topics; it simply passes the images to the `track` function as a numpy array. However, as per the official Ultralytics [documentation](https://docs.ultralytics.com/modes/predict/#inference-sources), images passed to this function are expected to be in BGR encoding.

<img src="https://github.com/Alpaca-zip/ultralytics_ros/assets/84959376/f069a898-a6da-4045-ad7d-37b19c253350" width="600px">

Given this, I would strongly advise ensuring that the image topics are in BGR encoding before utilizing my repository.

I acknowledge the need for conversion from various encodings to BGR, and I will certainly consider this as a future enhancement for the repository.

2023-08-08 08:48 UTC, Alpaca-zip commented on script/tracker_node.py
> +        	encoding = "bgr8"
- Your code uses tab for indentation, but please unify it with 4 spaces.
- `cv2.COLOR_RGBA2RGB` converts from RGBA to RGB and outputs in RGB order. However, `encoding = "bgr8"` indicates BGR order. 
```suggestion
            numpy_image = cv2.cvtColor(numpy_image, cv2.COLOR_RGBA2RGB)
            encoding = "rgb8"
```

2023-08-08 08:48 UTC, Alpaca-zip commented on script/tracker_node.py
> +        if numpy_image.shape[2] == 4:  # Check if the image has 4 channels
This section assumes that all 4-channel images are RGBA. If the original encoding is `bgra8` or `bgra16`, this could lead to bugs.

2023-08-08 08:53 UTC, Alpaca-zip commented
> Added a logic to handle 'bgr8a' encoding, usually found in simulation image sensors

You commented above, but looking at the code, I think you are assuming `rgba8`. Which is correct?

2023-08-08 10:29 UTC, Gowresh7 commented
Hello,

Thanks for the feedback. 

I just implemented this as a workaround because I was not able to make the code work for CARLA Simulation. I did not actually consider the ultralytics documentation. 

For some reason, I was able to make it work only with 'bgr8' encoding. Will check it out further and let you know.

2023-09-08 18:15 UTC, Alpaca-zip commented
Hello, @Gowresh7 .

This has already been improved in the https://github.com/Alpaca-zip/ultralytics_ros/pull/29. 
Feel free to re-open this PR if you have any more improvements. Thank you for your cooperation. 

Best regards,

2023-09-08 18:15 UTC, closed without merging